### ISSUE TITLE
Getting error Angular is loaded more than once on build

### ISSUE THREAD

**Issue by cramatt** [mobxjs/mobx-angularjs#2]
If I remove this line `import angular from 'angular';` the error goes away. 

Angular is not actually needed in that file so that line can be safely removed.

**Comment by adamkleingit** [comment]
How do you build the project? Which version are you using?

We need to import angular because we use it here:
```
const ngMobxModule = angular.module('ng-mobx', []);
```
And I cannot rely on it being defined globally.

**Comment by cramatt** [comment]
Hmm, yes you are correct. Any update here? I actually ran into this same issue when developing my own modules...

**Comment by cramatt** [comment]
I was able to fix this by including the src instead of the dist. Would be worth noting in the readme. 

`import 'ng-mobx/lib/ng-mobx';`

**Comment by nickbreaton** [comment]
This should be fixed by the new distribution type as UMD in 1.5.0.
