### ISSUE TITLE
Best practices?

### ISSUE THREAD

**Issue by scottschafer** [mobxjs/mobx-angularjs#20]
I'm looking at using this excellent looking library to retrofit a large AngularJS application where nearly everything is currently in the scope.

While I can follow what the the example is doing and why this directive is necessary here, I'm not sure what the best way to retrofit our code base is. For example, what should we do with existing code that uses "ng-click" or "ng-model" or anything that triggers a digest cycle? It seems to me that if we just referenced our mobx store through our scope and didn't change anything else, this directive wouldn't be necessary.

So...is the recommendation to use "onclick" instead of "ng-click" when triggering a mobx action, for example?

Thanks!

**Comment by kuitos** [comment]
Hi @scottschafer 
I had wrote an article which refer to your doubt, but wrote by Chinese, maybe u can read it with google translate, hopes that will be helpful for you. https://github.com/kuitos/kuitos.github.io/issues/38
Feel free to ask any other questions!
