### ISSUE TITLE
mobx-autorun link error

### ISSUE THREAD

**Issue by stephen-dahl** [mobxjs/mobx-angularjs#21]
line 1 of mobx-autorun link is
`var _a = $scope.$$watchers, $$watchers = _a === void 0 ? [] : _a;`
$scope.$$watchers is null for me when using angularjs 1.7.
this should be changed to `$$watchers = typeof _a !== 'array' ? [] : _a;`

**Comment by kuitos** [comment]
fixed and released v1.6.1
thanks for your feedback!
