### ISSUE TITLE
Error is $scope.$$watchers is null

### ISSUE THREAD

**Issue by cramatt** [mobxjs/mobx-angularjs#3]
https://github.com/500tech/ng-mobx/blob/master/lib/ng-mobx.js#L20

This happens if you use `mobx-autorun` and `ng-if` on the same element.

```
<div ng-if="!$ctrl.sessionStore.isLoggedIn()" mobx-autorun>
 // login
</div>
<div ng-if="$ctrl.sessionStore.isLoggedIn()" mobx-autorun>
  // logout
</div>
```

Moving mobx-autorun to a wrapper fixes the issue, but this is not always ideal.

```
<div mobx-autorun>
  <div ng-if="!$ctrl.sessionStore.isLoggedIn()">
   // login
  </div>
  <div ng-if="$ctrl.sessionStore.isLoggedIn()">
    // logout
  </div>
</div>
```

**Comment by cramatt** [comment]
I was also able to fix this by adding `priority: 999` to the ng-mobx directive, but not sure this ideal because it means the reaction never gets unbound ?

**Comment by aiboy** [comment]
You can use <template> it won't produce div element and allows you to avoid this bug

```
<template mobx-autorun>
  <div ng-if="!$ctrl.sessionStore.isLoggedIn()">
   // login
  </div>
  <div ng-if="$ctrl.sessionStore.isLoggedIn()">
    // logout
  </div>
</template>
```

**Comment by nickbreaton** [comment]
The null error should be fixed shortly, however, the `mobx-autorun` should be added to any element that creates a new scope. Such as `ng-if` of `ng-repeat`.
