### ISSUE TITLE
Unmet Peer Dependency

### ISSUE THREAD

**Issue by osdevisnot** [mobxjs/mobx-angularjs#4]
When using latest version of mobx - currently 3.1.0, we are getting below error from yarn install log:

warning "ng-mobx@1.2.2" has incorrect peer dependency "mobx@^2.6".

Does that mean ng-mobx is compatible only with mobx 2.x?

**Comment by nickbreaton** [comment]
For anyone wondering about this, this library depends on `reaction`, which was introduced in MobX 2.2.0. This will be updated in the package.json shortly.
