### ISSUE TITLE
distribution bundle size

### ISSUE THREAD

**Issue by osdevisnot** [mobxjs/mobx-angularjs#5]
It seems the `ng-mobx.js` in dist is very huge since we use webpack to bundle both angular and mobx. However, package json describes both angular and mobx are peer dependencies. Hence the bundling part seems incorrect.

**Comment by kuitos** [comment]
this repo seems not maintained any more, u can use https://github.com/mmlpxjs/mobx-angularjs instead, which forked from ng1-mobx 🙂

**Comment by adamkleingit** [comment]
Hey @kuitos , if you're up for maintaining it I would gladly point the users to your repository.

**Comment by kuitos** [comment]
@adamkleingit Thank you, that's my pleasure, I will continue to maintain it in a period of time 😀

**Comment by nickbreaton** [comment]
Should be fixed in v1.5.0
