### ISSUE TITLE
Any reason to use library instead of this code snippet?

### ISSUE THREAD

**Issue by xlc** [mobxjs/mobx-angularjs#6]
This will run all the watchers inside autorun and track all the dependencies, without using internal angular variables

```
mobx.autorunAsync('$rootScope#$digst', () => {
    $rootScope.$digest();
}, 2);
```

Please let me know if I missed anything

**Comment by adamkleingit** [comment]
Yes,
You code will run digest on the entire scope tree instead of just the components that need to be updated. Your app will pretty much be unusable if it gets bigger.
Also, if you're already in a digest cycle this will cause an error
