### ISSUE TITLE
Proposal for Maintainer Help and Official Support

### ISSUE THREAD

**Issue by nickbreaton** [mobxjs/mobx-angularjs#9]
Hello @adamkleingit.

This library has proven useful to me in the past few days. I hope to get my company to use it soon in order to ease a transition from AngularJS to React. I appreciate the time you put into it.

I had a few issues and noticed that @kuitos had forked and fixed most of them. It seems that you may not have had the time or desire to keep up with the maintenance of this project to merge them back in, [#5](https://github.com/NgMobx/ng1-mobx/issues/5#issuecomment-336030692), which is totally understandable when you are busy maintaining something like [mobxjs/mobx-angular](https://github.com/mobxjs/mobx-angular). I, on the other hand, do not have any open source projects to maintain and would love to help out.

If you are up for it, I propose that we make a few changes:

1. We could possibly move the repo under the [mobxjs organization](https://github.com/mobxjs) as `mobxjs/mobx-angularjs`, cc @mweststrate. 

2. Deprecate [ng-mobx](https://www.npmjs.com/package/ng-mobx) on npm, and align it with the same naming convention as [mobx-angular](https://www.npmjs.com/package/mobx-angular), publishing under `mobx-angularjs`, if that is okay with @kuitos.

3. Align the codebase with the conventions of `mobx-angular` and incorporate changes made by @kuitos. [I have done this here and will gladly submit a PR](https://github.com/nickbreaton/mobx-angularjs).

Cheers!

**Comment by kuitos** [comment]
Awesome proposal,will be glad to help with! 😃

**Comment by adamkleingit** [comment]
Hey guys, I will gladly add you as maintainers.
It's up to @mweststrate whether to put this in the main org. I think it will be less confusing for developers that way.

**Comment by adamkleingit** [comment]
Added the two of you.
Thanks for the contribution!

**Comment by nickbreaton** [comment]
Awesome thanks so much! I also am having second thoughts about renaming anything. I think it is just best to leave everything as `ng-mobx`.

**Comment by mweststrate** [comment]
Hey cool initiatives @nickbreaton  & @kuitos !

Moving is fine with me. @adamkleingit I think you should already have the permissions to move it. Otherwise invite me as collaborator, then I can probably move it

**Comment by adamkleingit** [comment]
Moved to https://github.com/mobxjs/ng1-mobx
But now I don't have admin permissions on it so I can't add collaborators / change its name to mobx-angularjs. @mweststrate can you make me admin?

**Comment by mweststrate** [comment]
Done

Op ma 22 jan. 2018 om 10:01 schreef adam klein <notifications@github.com>:

**Comment by kuitos** [comment]
A great evolution for mobx-angularjs! 
Do you think is it necessary to publish it under `mobx-angularjs` on npm from then on? @nickbreaton @adamkleingit

**Comment by nickbreaton** [comment]
@kuitos I think that might be the better solution so that the name stays consistent for users. I will update the package name and repository URL in the PR.

@mweststrate Thanks for weighing in! 😄

**Comment by kuitos** [comment]
@adamkleingit @nickbreaton  Added you two as `mobx-angularjs` package collaborators.

**Comment by adamkleingit** [comment]
Great. I deprecated ng-mobx
